version: '3.3'

services:
  tomcat:
    build:
      context: .
      dockerfile: Application.Dockerfile
    image: e-commerce
    container_name: e-commerce
    ports:
      - 8085:8080
    logging:
      driver: splunk
      options:
        splunk-url: https://172.17.0.2:8088
        splunk-token: "9b80162d-02ba-445c-aabc-95e29308c818"
        splunk-insecureskipverify: 'true'

  jenkins:
    build:
      context: .
      dockerfile: Jenkins.Dockerfile
    image: jenkins
    container_name: jenkins
    restart: on-failure
    environment:
      JENKINS_USER: ecommerce
      JENKINS_PASSWORD: udacity
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
