version: '3.3'

services:
  tomcat:
    build:
      context: .
      dockerfile: Application.Dockerfile
    image: e-commerce
    container_name: e-commerce
    ports:
      - 8085:8080

  jenkins:
    build:
      context: .
      dockerfile: Jenkins.Dockerfile
    image: jenkins
    container_name: jenkins
    restart: on-failure
    environment:
      JENKINS_USER: ecommerce
      JENKINS_PASSWORD: udacity
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
