version: '3.3'

services:
  tomcat:
    build:
      context: .
      dockerfile: Tomcat.Dockerfile
    image: udacity-tomcat
    container_name: udacity-tomcat
    ports:
      - 8080:8080
    networks:
      - cluster_network

    # logging:
    #  driver: splunk
    #  options:
    #    splunk-url: https://172.17.0.2:8088
    #    splunk-token: ""
    #    splunk-insecureskipverify: 'true'

  jenkins:
    build:
      context: .
      dockerfile: Jenkins.Dockerfile
    image: udacity-jenkins
    container_name: udacity-jenkins
    restart: on-failure
    environment:
      JENKINS_USER: ecommerce
      JENKINS_PASSWORD: udacity
      TOMCAT_USER: udacity
      TOMCAT_PASSWORD: ecommerce
      TOMCAT_ADDRESS: udacity-tomcat
      TOMCAT_PORT: 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:8080
    networks:
      - cluster_network

networks:
  cluster_network:
      driver: bridge
