pipeline {

    agent any

    environment {
        JENKINS_JOB = "e-Commerce"
        PROJECT_REPOSITORY_DIRECTORY = "eCommerce"
        APPLICATION_DIRECTORY = "$WORKSPACE/$JENKINS_JOB/$PROJECT_REPOSITORY_DIRECTORY"
    }

    options {
        skipDefaultCheckout()
        skipStagesAfterUnstable()
    }

    stages {

        stage ('SCM Checkout') {

            steps {
                checkout scm
            }

        }

        stage ('Build') {

            steps {
                dir($APPLICATION_DIRECTORY) {
                    script {
                        docker.image("maven:3.6.3-openjdk-8-slim").inside() {
                            sh 'mvn -B -DskipTests clean package'
                        }
                    }
                }
            }

        }

        stage ('Test') {

            when {
                anyOf {
                    changeset "${APPLICATION_DIRECTORY}/**/*"
                }
            }

            steps {

                script {
                    docker.image("maven:3.6.3-openjdk-8-slim").inside() {
                        sh 'mvn test'
                    }
                }

                post {
                    always {
                        junit 'target/surefire-reports/*.xml'
                    }
                }

            }

        }

        stage ('Deploy') {

            when {
                anyOf {
                    changeset "${APPLICATION_DIRECTORY}/**/*"
                }
            }

            steps {
                script {
                    sh 'echo $APPLICATION_DIRECTORY'
                }
            }

        }

    }   // Stages

}       // Pipeline
