pipeline {

    agent {

        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }

    }

    environment {
        APPLICATION_DIRECTORY = 'eCommerce'
    }

    options {
        skipDefaultCheckout()
        skipStagesAfterUnstable()
    }

    stages {

        stage ('SCM Checkout') {

            steps {
                checkout scm
            }

        }

        stage ('Build') {

            steps {
                script {
                    sh 'mvn -B -DskipTests clean package'
                }
            }

        }

        stage ('Test') {

            when {
                anyOf {
                    changeset "${APPLICATION_DIRECTORY}/**/*"
                }
            }

            steps {

                script {
                    sh 'mvn test'
                }

                post {
                    always {
                        junit 'target/surefire-reports/*.xml'
                    }
                }

            }

        }

        stage ('Deploy') {

            when {
                anyOf {
                    changeset "${APPLICATION_DIRECTORY}/**/*"
                }
            }

            steps {
                script {
                    sh 'echo $HOME'
                }
            }

        }

    }   // Stages

}       // Pipeline
